---
title: "Using R in neuroscience research"
output: html_document
---

#### Website

https://andrewli-nurc.netlify.app

#### About this workshop

__What it is:__ This is a hands on introduction aimed to beginners. The goal is to get participants familiar and enthusiastic with the R programming language. As well, to know how to access additional resources/courses to continue learning on their own.

__Who is it for:__ This workshop is aimed towards researchers who are interested in using R but have little or no programming experience. This will be a  gentle introduction to R and Jupyter.


#### Details

__Time:__ The workshop officially starts at 7:25pm but the instructors will be online earlier (~7pm) to chat and answer questions. <br>
__Date:__ Thursday, January 28th 2021 <br>
__Place:__ The Zoom link can be found [here](https://docs.google.com/document/d/1lJyHPvEm95x79rmCJJ_T7y-FBYDSWBu77u9C_flKw3Q/edit?fbclid=IwAR3X9tTpT9hApd5i4wIOZW3YvwhncILjdpJ1bx4-0E59UKqnamXRNmbmQLY#heading=h.urw1vzli8gz5).

#### Instructor

[Andrew Li](http://andrewcli.me) <br>
[Tiger Wu](https://tigerthepro.github.io/TigerWu/)

#### Content
* Introduction to Jupyter 
* Read in data via `readr`
  * `read_csv()`
* Data cleaning via `dplyr`
  * `filter()`
  * `select()`
  * `rename()`
  * `mutate()`
* Data visualization via `ggplot2`
  * The [grammar of graphics](https://www.amazon.ca/Grammar-Graphics-Leland-Wilkinson/dp/0387245448)
  * `geom_boxplot()`
  * `geom_point()`
  * [Default themes](https://ggplot2.tidyverse.org/reference/ggtheme.html)
* The pipe operator `%>%`

#### Registration
Attendance is free, please RSVP [here](https://docs.google.com/forms/d/e/1FAIpQLSco1157Ttx7Ml64UJlMddTQHWRV7x6JFuR1s16f6luWTUkp2A/viewform)! For questions please email the [Neuroscience Club](mailto:ubcneuroscienceclub@gmail.com).

#### Research Opportunity
If you are an undergrad student looking for research opportunity in psychiatry, shoot [me](mailto:andrewlll9@hotmail.ca) an email!
