---
title: "Software Installation"
output: html_document
---

In order to get started with this workshop, you *might* need to download some tools. 

#### Jupyter Notebook
You can access Jupyter notebooks via [ubc.syzygy.ca](https://ubc.syzygy.ca/). I highly recommend you use this method if you have a CWL account. Alternatively, you can log in with a google account via [cybera.syzygy.ca](https://cybera.syzygy.ca/). From here, simply upload the .ipynb file and you will be able to access it. If these two methods don't work, you can follow the instructions below.


{{% callout note %}}
If you have a UBC CWL or google account, I suggest you use Jupyter notebook via syzygy as you will not need to download anything!
{{% /callout %}}

{{% callout note %}}
If you are using Jupyter notebook, you __cannot__ upload the `workshop_name` folder (you can only upload files not folders). Instead of manually uploading everything,  follow these steps:

1. After you download it, find it in your downloads and zip (compress) it.

2. Upload the .zip file into Jupyter home

3. In Jupyter home, open a new Terminal and run:

``` 
! unzip ~/workshop_name.zip -d ~/
```
4. If you want to delete the .zip file, you can delete it manually or run 

```
rm ~/workshop_name.zip
```

5. Open the folder and find the .ipynb file!
{{% /callout %}}

#### Jupyter Lab/Python/conda
You need to install Python to run Jupyter Lab. As well, you will need package manager. You can install that [here](https://docs.conda.io/en/latest/miniconda.html) (make sure you download `Miniconda MacOSX 64-bit bash`). From there, you can install Jupyter Lab via `conda`:

```
conda install -c conda-forge jupyterlab
```
#### R and R Studio
For this workshop, we will be conducting our analysis via the R programming language, as such you need to install R. You do not need to install R Studio, but I suggest you do so for your future R endeavors. 

* Download __R__ [here](https://mirror.rcg.sfu.ca/mirror/CRAN/). 
* Download __R Studio__ [here](https://rstudio.com/products/rstudio/download/). 

#### IRkernel
You need to download the `IRkernal` package in order to use R in Jupyter notebooks. To do so, simply install the pacakge via R Studio:

```
install.packages("IRkernel")
```

Then, open your terminal and paste the following code:

```
R -e "IRkernel::installspec()"
```

After that, you should be able to use R in Jupyter now! To check, simply type jupyter lab in your terminal and see if you can create a new notebook using the R language. 

```
jupyter lab
```

#### Acknowledgement
* [UBC Master of Data Science Install Guide](https://ubc-mds.github.io/resources_pages/installation_instructions/)






