---
title: "NURC Workshop Materials"
output: 
  html_document:
    toc: true
    toc_float: true
---

#### About this workshop

__What it is:__ This is a hands on introduction aimed to beginners. The goal is to get participants familiar and enthusiastic with the R programming language. As well, to know how to access additional resources/courses to continue learning on their own.

__Who is it for:__ This workshop is aimed towards researchers who are interested in using R but have little or no programming experience. This will be a  gentle introduction to R and Jupyter.

#### Problem set(s)

| Problem set | Download   | Preview            | Topic(s)                                                                             | # of questions |
|-------------|------------|--------------------|--------------------------------------------------------------------------------------|----------------|
| nurc_2021   | <a href="/content/problem_sets/nurc_2021.zip" class="text-link">.zip</a>| [View on GitHub](https://github.com/andr3wli/nurc-r-website/blob/master/content/problem_sets/nurc_2021_folder/nurc_2021.ipynb) | * Intro to Jupyter <br>* Reading in Data<br>* Data wrangling<br>* Data visualization<br> * The pipe operator | 20             |

#### Details

__Time:__ The workshop officially starts at 7:25pm but the instructors will be online earlier (~7pm) to chat and answer questions. <br>
__Date:__ Thursday, January 28th 2021 <br>
__Place:__ The Zoom link can be found [here](https://docs.google.com/document/d/1lJyHPvEm95x79rmCJJ_T7y-FBYDSWBu77u9C_flKw3Q/edit?fbclid=IwAR3X9tTpT9hApd5i4wIOZW3YvwhncILjdpJ1bx4-0E59UKqnamXRNmbmQLY#heading=h.urw1vzli8gz5). <br>
__Instructors:__ [Andrew Li](http://andrewcli.me) and [Tiger Wu](https://tigerthepro.github.io/TigerWu/)  <br>
__Registration:__ Attendance is free, please RSVP [here](https://docs.google.com/forms/d/e/1FAIpQLSco1157Ttx7Ml64UJlMddTQHWRV7x6JFuR1s16f6luWTUkp2A/viewform)!

#### Downloading the problem set
To download the problem sets, simply right click the .zip file and download/save it. If you want to take a look at the problems/content, you can check it out on GitHub.

#### Loading the problem set
To load the problem set, simply type `jupyter lab` or `jupyter notebook` in your terminal. Then, find the nurc_2021 folder and open then find the .ipynb file.  

```
    (base) Andrews-MacBook-Pro:~ andrewli$ jupyter lab
```
Alternatively, you can open the problem set via __UBC Syzygy__ (I recommend this way if you have an UBC CWL).

1. Go to [ubc.syzygy.ca](https://ubc.syzygy.ca/).
2. Sign in with your CWL account.
3. Check below!

You can log in with your google account via __Cybera__ if you do not have an UBC CWL.

1. Go to [cybera.syzygy.ca](https://cybera.syzygy.ca).
2. Sign in with your google account.
3. Check below!

{{% callout note %}}
If you are using Jupyter notebook, you __cannot__ upload the `nurc_2021` folder (you can only upload files not folders). Instead of manually uploading everything,  follow these steps:

~~1. After you download it, find it in your downloads and zip (compress) it.~~ The file is zipped already!

2. Upload the .zip file into Jupyter home

3. In Jupyter home, open a new Terminal and run:

``` 
! unzip ~/nurc_2021.zip -d ~/
```
4. If you want to delete the .zip file, you can delete it manually or run 

```
rm ~/nurc_2021.zip
```

5. Open the folder and find the .ipynb file!
{{% /callout %}}

#### Contents
In this workshop, we will use a FMRI data set that explores [Alzheimer's disease](https://www.kaggle.com/jboysen/mri-and-alzheimers). You will be introduced to the basics of reading in data, data wrangling, and data visualization. Next we will work with data set that looks at [traumatic brain injury](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-03-24/readme.md) demonstrate how powerful and customizable ggplot2 is. After making a basic ggplot2 plot, we will make it more aesthetically pleasing by changing the axis names, themes, font, and more! 

* Introduction to Jupyter 
* Read in data via `readr`
  * `read_csv()`
* Data cleaning via `dplyr`
  * `filter()`
  * `select()`
  * `rename()`
  * `mutate()`
* Data visualization via `ggplot2`
  * The [grammar of graphics](https://www.amazon.ca/Grammar-Graphics-Leland-Wilkinson/dp/0387245448)
  * `geom_boxplot()`
  * `geom_point()`
  * [Default themes](https://ggplot2.tidyverse.org/reference/ggtheme.html)
* The pipe operator `%>%`
